@startuml
'https://plantuml.com/class-diagram

class main{
makes file address
processInputFiles
readUserInput

Print Output
}
class readUserInput{
Takes in user Input
}
class processInputFile{
makes File into an ArrayList
make exception in not found
}
class GenerateOutputString{
generate the String output
}

main-->processInputFile
main-->readUserInput
readUserInput->GenerateOutputString
GenerateOutputString->main
@enduml